services:
  backend:
    build: ./backend
    command: sh -c "npx prisma migrate deploy && node app.js"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env  
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - backend

  db:
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data: